"""Render the blueprint's factual sections from a run artifact.

The blueprint used to state its numbers in hand-typed prose. Every one of them
was wrong: a parameter count from an older architecture, a vocabulary size that
matched no version of the code, loss curves nobody could reproduce, seven
assertions that did not exist. The numbers were not wrong because anyone lied.
They were wrong because a human typed them once and the code kept moving.

So this module is the fix for the root cause, not for the numbers. It reads
``runs/latest.json`` - the artifact ``glassbox.export`` writes - and renders the
factual sections of the document as Markdown. Nothing here computes a model
quantity, and nothing here has a fallback value: if a field is missing from the
artifact the table says so in the output instead of substituting something
plausible. A claim you cannot trace to a field in the artifact is a claim this
module will not print.

Usage::

    python -m glassbox.report                              # print to stdout
    python -m glassbox.report --section results             # one section
    python -m glassbox.report --update Glassbox_Course_Blueprint.md

``--update`` rewrites only the text between paired HTML comments::

    <!-- BEGIN generated:results -->
    ...replaced...
    <!-- END generated:results -->

Everything outside those markers is hand-written prose and is never touched.
The rewrite is idempotent: running it twice produces a byte-identical file.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_RUN = REPO_ROOT / "runs" / "latest.json"

#: Printed wherever the artifact does not carry the field. Never a number.
ABSENT = "absent from artifact"

BEGIN = "<!-- BEGIN generated:{name} -->"
END = "<!-- END generated:{name} -->"
MARKER_RE = re.compile(
    r"(?P<begin><!--\s*BEGIN generated:(?P<name>[a-z0-9_-]+)\s*-->)"
    r"(?P<body>.*?)"
    r"(?P<end><!--\s*END generated:(?P=name)\s*-->)",
    re.DOTALL,
)

GENERATED_NOTE = (
    "<!-- Generated by `python -m glassbox.report --update` from "
    "runs/latest.json. Do not edit by hand; edit the run, then regenerate. -->"
)


# --------------------------------------------------------------------------
# Artifact access. Every read goes through _get so a missing field degrades to
# a printed "absent from artifact" rather than a KeyError or an invented value.
# --------------------------------------------------------------------------


def load_run(path: Path = DEFAULT_RUN) -> Dict[str, Any]:
    """Load a run artifact written by :mod:`glassbox.export`."""
    with open(path, "r", encoding="utf-8") as fh:
        run = json.load(fh)
    if not isinstance(run, dict):
        raise ValueError(f"{path}: run artifact must be a JSON object")
    return run


def _get(obj: Any, *path: Any) -> Any:
    """Walk dict keys and list indices, returning None at the first miss."""
    cur = obj
    for step in path:
        if isinstance(step, int) and isinstance(cur, list):
            if -len(cur) <= step < len(cur):
                cur = cur[step]
                continue
            return None
        if isinstance(cur, dict) and step in cur:
            cur = cur[step]
            continue
        return None
    return cur


# --------------------------------------------------------------------------
# Display formatting. Rounding happens here and only here; the artifact keeps
# the full-precision values.
# --------------------------------------------------------------------------


def num(value: Any, decimals: int = 4) -> str:
    """Format one number for display, or say the field is missing."""
    if value is None:
        return ABSENT
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, float):
        return f"{value:.{decimals}f}"
    return str(value)


def pct(value: Any, decimals: int = 1) -> str:
    if value is None:
        return ABSENT
    return f"{value * 100:.{decimals}f}%"


def arrow(start: Any, end: Any, decimals: int = 4) -> str:
    return f"{num(start, decimals)} -> {num(end, decimals)}"


def _compact(value: Any, decimals: int = 7, maxlen: int = 40) -> str:
    """A short, cell-safe rendering of an arbitrary JSON value."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        # Keep a trailing ".0" so a float hyperparameter never reads as an int.
        if value.is_integer() and abs(value) < 1e6:
            return f"{value:.1f}"
        return f"{value:.{decimals}g}"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return value if len(value) <= maxlen else value[: maxlen - 1] + "\u2026"
    if isinstance(value, list):
        if not value:
            return "[]"
        if all(not isinstance(v, (list, dict)) for v in value):
            shown = ", ".join(_compact(v, decimals, maxlen) for v in value[:4])
            more = f", \u2026 (+{len(value) - 4})" if len(value) > 4 else ""
            return f"[{shown}{more}]"
        return f"[{len(value)} entries]"
    if isinstance(value, dict):
        return "{" + ", ".join(
            f"{k}: {_compact(v, decimals, maxlen)}"
            for k, v in list(value.items())[:3]
        ) + ("}" if len(value) <= 3 else ", \u2026}")
    return str(value)


def _approx_seconds(value: Any) -> str:
    """Wall-clock rounded to the nearest 10 seconds, as an approximation."""
    try:
        seconds = float(value)
    except (TypeError, ValueError):
        return "unrecorded"
    return f"about {int(round(seconds / 10.0) * 10)} s on one CPU"


def cell(text: str) -> str:
    """Make a string safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
    """Render a Markdown table. Rows are already-formatted strings."""
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        out.append("| " + " | ".join(cell(str(c)) for c in row) + " |")
    return "\n".join(out)


# --------------------------------------------------------------------------
# Stage descriptors. The results table is data, not code: a new stage is a new
# entry here, and a stage whose metric is renamed shows up as missing rather
# than silently keeping the old number.
# --------------------------------------------------------------------------

#: (metric label, key in the history rows, decimals)
Metric = Tuple[str, str, int]

STAGE_SPECS: List[Dict[str, Any]] = [
    {
        "key": "pretrain",
        "label": "Pretraining",
        "counter": ("steps", "step"),
        "metrics": [
            ("train loss (next token, 8 paragraphs)", "train", 4),
            ("validation loss (2 held-out paragraphs)", "validation", 4),
        ],
    },
    {
        "key": "sft",
        "label": "Full SFT",
        "counter": ("steps", "step"),
        "metrics": [
            ("answer-token loss", "train", 4),
            ("prose validation loss (retention)", "retention", 4),
        ],
    },
    {
        "key": "lora_sft",
        "label": "LoRA SFT",
        "counter": ("steps", "step"),
        "metrics": [
            ("answer-token loss", "train", 4),
            ("prose validation loss (retention)", "retention", 4),
        ],
    },
    {
        "key": "reward_model",
        "label": "Reward model",
        "counter": ("steps", "step"),
        "metrics": [
            ("Bradley-Terry loss", "loss", 4),
            ("pair ranking accuracy", "ranking_accuracy", 3),
            ("mean score margin", "mean_margin", 4),
        ],
    },
    {
        "key": "dpo",
        "label": "DPO",
        "counter": ("steps", "step"),
        "metrics": [
            ("DPO loss", "loss", 6),
            ("implied-reward margin", "margin", 4),
            ("pair accuracy", "accuracy", 3),
            ("policy log-prob of chosen", "policy_chosen_logprob", 4),
            ("policy log-prob of rejected", "policy_rejected_logprob", 4),
        ],
    },
    {
        "key": "warm_start",
        "label": "Warm start (SFT on task demonstrations)",
        "counter": ("steps", "step"),
        "metrics": [
            ("answer-token loss", "train", 4),
            ("prose validation loss (retention)", "retention", 4),
        ],
    },
    {
        "key": "grpo",
        "label": "GRPO on verifiable tasks",
        "counter": ("iterations", "iteration"),
        "metrics": [
            ("mean verifier reward", "mean_reward", 3),
            ("clipped fraction", "clipped_fraction", 3),
            ("KL to reference", "kl", 4),
            ("policy loss", "policy_loss", 4),
        ],
    },
]


def _history_endpoints(run: Dict[str, Any], key: str) -> Tuple[Any, Any]:
    hist = _get(run, "stages", key, "history")
    if not isinstance(hist, list) or not hist:
        return None, None
    return hist[0], hist[-1]


# --------------------------------------------------------------------------
# Sections
# --------------------------------------------------------------------------


def section_configuration(run: Dict[str, Any]) -> str:
    m = _get(run, "manifest") or {}
    model = _get(m, "model") or {}
    lines = ["#### Architecture as it actually ran", ""]
    arch_rows = [
        ("architecture", "decoder-only causal transformer"),
        ("layers", num(_get(model, "layers"))),
        ("residual width", num(_get(model, "width"))),
        ("attention heads", num(_get(model, "heads"))),
        ("head width", num(_get(model, "head_dim"))),
        ("MLP width", num(_get(model, "mlp_width"))),
        ("context limit", num(_get(model, "context"))),
        ("vocabulary size", num(_get(model, "vocab_size"))),
        ("total parameters", num(_get(m, "parameters"))),
        ("position encoding", str(_get(model, "position") or ABSENT)),
        ("normalization", str(_get(model, "normalization") or ABSENT)),
        ("activation", str(_get(model, "activation") or ABSENT)),
        ("input/output embedding tied", num(_get(model, "output_embedding_tied"))),
        ("dropout", num(_get(model, "dropout"), 2)),
        ("initialisation std", num(_get(model, "init_std"), 3)),
        ("seed", num(_get(m, "seed"))),
        ("device", str(_get(m, "device") or ABSENT)),
    ]
    lines.append(table(["Field", "Value"], [[k, v] for k, v in arch_rows]))

    vocab = _get(model, "vocab_size")
    if isinstance(vocab, int) and vocab > 0:
        import math

        lines += [
            "",
            f"An untrained model over {vocab} tokens has no preference between "
            f"them, so its cross-entropy starts at ln({vocab}) = "
            f"{math.log(vocab):.4f} nats. Every loss below is in nats per token "
            "and is comparable to that figure.",
        ]

    lines += ["", "#### Data as it actually ran", ""]
    data_rows = [
        ("training paragraphs", num(len(_get(run, "data", "paragraphs") or []))),
        ("validation paragraphs",
         num(len(_get(run, "data", "validation_paragraphs") or []))),
        ("training windows", num(_get(m, "num_train_windows"))),
        ("validation windows",
         num(_get(run, "stages", "pretrain", "num_validation_windows"))),
        ("SFT instruction examples",
         num(_get(run, "stages", "sft", "num_examples"))),
        ("warm-start demonstrations",
         num(_get(run, "stages", "warm_start", "num_examples"))),
        ("preference pairs", num(_get(run, "stages", "reward_model", "num_pairs"))),
        ("character tokenizer size",
         num(_get(run, "stages", "tokenizers", "character", "size"))),
        ("subword tokenizer size (train-only fit)",
         num(_get(run, "stages", "tokenizers", "subword", "size"))),
        ("subword merges learned",
         num(_get(run, "stages", "tokenizers", "subword", "num_merges"))),
    ]
    fam = _get(run, "data", "instruction_families")
    if isinstance(fam, dict):
        for name, items in fam.items():
            data_rows.append((f"instruction family `{name}`", num(len(items))))
    tasks = _get(run, "data", "task_families")
    if isinstance(tasks, dict):
        for name, items in tasks.items():
            data_rows.append((f"task family `{name}`", num(len(items))))
    lines.append(table(["Field", "Count"], [[k, v] for k, v in data_rows]))

    cfgs = _get(m, "stage_configs")
    if isinstance(cfgs, dict):
        lines += ["", "#### Stage hyperparameters as they actually ran", ""]
        rows = []
        for stage, cfg in cfgs.items():
            if not isinstance(cfg, dict):
                continue
            for field, value in cfg.items():
                rows.append([f"`{stage}`", field, _compact(value, maxlen=170)])
        lines.append(table(["Stage", "Field", "Value"], rows))
    return "\n".join(lines)


def section_results(run: Dict[str, Any]) -> str:
    lines = ["#### Measured results, one row per stage metric", ""]
    rows: List[List[str]] = []
    for spec in STAGE_SPECS:
        first, last = _history_endpoints(run, spec["key"])
        cfg_field, hist_field = spec["counter"]
        count = _get(run, "stages", spec["key"], "config", cfg_field)
        if count is None:
            count = _get(last, hist_field)
        label = spec["label"]
        if first is None:
            rows.append([label, ABSENT, ABSENT, ABSENT, ABSENT])
            continue
        for i, (metric, key, dec) in enumerate(spec["metrics"]):
            rows.append([
                label if i == 0 else "",
                f"{num(count)} {cfg_field}" if i == 0 else "",
                metric,
                num(_get(first, key), dec),
                num(_get(last, key), dec),
            ])
    lines.append(table(["Stage", "Length", "Metric", "Start", "End"], rows))

    best = _get(run, "stages", "pretrain", "best_validation")
    final_val = _get(run, "stages", "pretrain", "final", "validation")
    if isinstance(best, dict):
        bv = _get(best, "validation")
        direction = (
            "higher than" if (bv is not None and final_val is not None and final_val > bv)
            else "not worse than"
        )
        lines += [
            "",
            f"Best validation loss during pretraining was {num(bv)} at step "
            f"{num(_get(best, 'step'))}. The final step's validation loss is "
            f"{num(final_val)}, which is {direction} the best. The last "
            "checkpoint is therefore not the best checkpoint, which is what "
            "makes early stopping a demonstrable lesson here rather than an "
            "assertion.",
        ]

    lines += ["", "#### Did the transformer earn its parameters?", ""]
    base = _get(run, "stages", "evaluation", "baselines")
    if not isinstance(base, dict):
        lines += [
            f"Baseline comparison {ABSENT}: this artifact carries no "
            "`stages.evaluation.baselines` block, so no baseline claim is made "
            "here. Rebuild the run with a current `glassbox.export` to populate "
            "it.",
        ]
    else:
        model_train = _get(run, "stages", "pretrain", "final", "train")
        model_val = _get(run, "stages", "pretrain", "final", "validation")
        rows = [
            ["uniform over the vocabulary",
             num(_get(base, "train", "uniform")),
             num(_get(base, "validation", "uniform"))],
            ["unigram + Laplace (train-split counts)",
             num(_get(base, "train", "unigram_laplace")),
             num(_get(base, "validation", "unigram_laplace"))],
            ["bigram + Laplace (train-split counts)",
             num(_get(base, "train", "bigram_laplace")),
             num(_get(base, "validation", "bigram_laplace"))],
            ["**the `base` checkpoint**", f"**{num(model_train)}**",
             f"**{num(model_val)}**"],
        ]
        lines.append(table(["Model", "Train loss", "Validation loss"], rows))
        scored = _get(base, "validation", "scored_positions")
        lines += [
            "",
            f"All four are scored on exactly the same "
            f"{num(scored)} validation positions, and the two count models were "
            "fitted on the training split only.",
        ]
        rivals = {
            "uniform": _get(base, "validation", "uniform"),
            "unigram": _get(base, "validation", "unigram_laplace"),
            "bigram": _get(base, "validation", "bigram_laplace"),
        }
        known = {k: v for k, v in rivals.items() if v is not None}
        if model_val is not None and known:
            lines.append("")
            beaten = [k for k, v in known.items() if model_val < v]
            lost = [k for k, v in known.items() if model_val >= v]
            if not lost:
                lines.append(
                    "The model beats all three "
                    f"({', '.join(f'{k} {num(v)}' for k, v in known.items())}), "
                    "so the falling curve is evidence of learning and not just "
                    "evidence of leaving a broken initialisation."
                )
            else:
                lines.append(
                    "The model beats "
                    f"{', '.join(beaten) if beaten else 'none of the baselines'} "
                    f"but LOSES to {', '.join(lost)}. A transformer that does "
                    "not beat a bigram count model has not earned its "
                    "parameters, and this run has not."
                )

    lines += ["", "#### Preference optimisation, pair by pair", ""]
    pairs = _get(run, "stages", "dpo", "pairs")
    if not isinstance(pairs, list) or not pairs:
        lines.append(f"DPO pair detail {ABSENT}.")
    else:
        rows = []
        for i, p in enumerate(pairs):
            rows.append([
                str(i),
                num(_get(p, "policy_chosen")),
                num(_get(p, "reference_chosen")),
                num(_get(p, "policy_rejected")),
                num(_get(p, "reference_rejected")),
                num(_get(p, "margin")),
            ])
        lines.append(table(
            ["Pair", "policy log p(chosen)", "reference log p(chosen)",
             "policy log p(rejected)", "reference log p(rejected)", "margin"],
            rows,
        ))
        dropped = [
            i for i, p in enumerate(pairs)
            if _get(p, "policy_chosen") is not None
            and _get(p, "reference_chosen") is not None
            and _get(p, "policy_chosen") < _get(p, "reference_chosen")
        ]
        if dropped:
            lines += [
                "",
                f"In {len(dropped)} of {len(pairs)} pairs the trained policy "
                "assigns the CHOSEN answer a LOWER log-probability than the "
                "frozen reference did. DPO's margin is a difference of "
                "differences: pushing the rejected answer down far enough "
                "raises the margin even while the preferred answer also becomes "
                "less likely. The margin improved; the chosen answer did not.",
            ]

    lines += ["", "#### GRPO, including the parts that did not work", ""]
    hist = _get(run, "stages", "grpo", "history")
    if not isinstance(hist, list) or not hist:
        lines.append(f"GRPO history {ABSENT}.")
    else:
        rewards = [h.get("mean_reward") for h in hist if h.get("mean_reward") is not None]
        best_iter = max(hist, key=lambda h: h.get("mean_reward", float("-inf")))
        zero_var = sum(h.get("zero_variance_groups", 0) or 0 for h in hist)
        groups = sum(h.get("num_groups", 0) or 0 for h in hist)
        clipped = [h.get("clipped_fraction") for h in hist
                   if h.get("clipped_fraction") is not None]
        rows = [
            ["iterations", num(len(hist))],
            ["mean reward, first -> last iteration",
             arrow(rewards[0] if rewards else None,
                   rewards[-1] if rewards else None, 3)],
            ["best mean reward",
             f"{num(_get(best_iter, 'mean_reward'), 3)} at iteration "
             f"{num(_get(best_iter, 'iteration'))}"],
            ["zero-variance groups",
             f"{num(zero_var)} of {num(groups)} groups "
             f"({pct(zero_var / groups) if groups else ABSENT})"],
            ["maximum clipped fraction in any iteration",
             num(max(clipped), 3) if clipped else ABSENT],
            ["KL to reference, first -> last",
             arrow(_get(hist[0], "kl"), _get(hist[-1], "kl"))],
            ["verifier", str(_get(run, "manifest", "stage_configs", "grpo",
                                  "verifier") or ABSENT)],
            ["reward rule", str(_get(run, "stages", "grpo", "verifier_note") or ABSENT)],
        ]
        lines.append(table(["Quantity", "Value"], rows))
        if groups:
            lines += [
                "",
                f"{num(zero_var)} of {num(groups)} sampled groups had zero "
                "reward variance. Every completion in such a group scores the "
                "same, the group-relative advantage is exactly zero, and that "
                "iteration's policy gradient carries no information from those "
                "prompts. That is roughly "
                f"{pct(zero_var / groups)} of the sampling budget spent for no "
                "learning signal - the single most common way a small-model "
                "RLVR run quietly fails.",
            ]

    verifiers = _get(run, "stages", "verifier_table")
    if isinstance(verifiers, list) and verifiers:
        lines += ["", "#### Three verifiers on the same completions", ""]
        rows = []
        for v in verifiers:
            text = _get(v, "completion")
            shown = (
                "_(empty completion)_" if text == ""
                else "`" + _compact(text, maxlen=60).replace("\n", "\\n") + "`"
            )
            rows.append([
                shown,
                num(_get(v, "answer")),
                num(_get(v, "strict")),
                num(_get(v, "substring_broken")),
                num(_get(v, "process")),
            ])
        lines.append(table(
            ["Completion", "Answer", "strict", "substring (broken)", "process"],
            rows,
        ))
        lines += [
            "",
            "The broken substring verifier awards reward for `answer: 25` when "
            "the answer is 5, and the process verifier refuses a correct final "
            "answer reached through wrong intermediate arithmetic. A reward "
            "number is only as meaningful as the function that produced it.",
        ]
    return "\n".join(lines)


def section_lora(run: Dict[str, Any]) -> str:
    lora = _get(run, "stages", "lora_sft", "lora")
    sft_first, sft_last = _history_endpoints(run, "sft")
    lora_first, lora_last = _history_endpoints(run, "lora_sft")
    if lora_last is None or sft_last is None:
        return f"LoRA comparison {ABSENT}."

    rows = [
        ["trainable parameters",
         num(_get(run, "manifest", "parameters")),
         f"{num(_get(lora, 'trainable_parameters'))} "
         f"({pct(_get(lora, 'trainable_fraction'), 1)} of "
         f"{num(_get(lora, 'frozen_parameters'))})"],
        ["answer-token loss, start -> end",
         arrow(_get(sft_first, "train"), _get(sft_last, "train")),
         arrow(_get(lora_first, "train"), _get(lora_last, "train"))],
        ["prose validation loss, start -> end",
         arrow(_get(sft_first, "retention"), _get(sft_last, "retention")),
         arrow(_get(lora_first, "retention"), _get(lora_last, "retention"))],
    ]
    fam = _get(run, "stages", "evaluation", "comparison")
    if isinstance(fam, dict):
        cps = _get(fam, "checkpoints") or []
        for row in _get(fam, "rows") or []:
            if _get(row, "group") != "instruction_exact_match":
                continue
            vals = _get(row, "values") or []
            pick = {}
            for name in ("sft", "lora"):
                if name in cps and len(vals) > cps.index(name):
                    pick[name] = vals[cps.index(name)]
            if len(pick) == 2:
                rows.append([
                    f"instruction exact match, `{_get(row, 'metric')}` family",
                    num(pick["sft"], 3), num(pick["lora"], 3),
                ])
    lines = [
        "The two runs see the SAME data with the SAME objective and the SAME "
        "number of steps. They differ only in which parameters are allowed to "
        "move.",
        "",
        table(["Quantity", "Full SFT", "LoRA SFT"], rows),
    ]

    sft_train = _get(sft_last, "train")
    lora_train = _get(lora_last, "train")
    sft_ret = _get(sft_last, "retention")
    lora_ret = _get(lora_last, "retention")
    if None not in (sft_train, lora_train, sft_ret, lora_ret):
        learned_less = lora_train > sft_train
        forgot_less = lora_ret < sft_ret
        if learned_less and forgot_less:
            lines += [
                "",
                f"LoRA fit the task less well ({num(lora_train)} against "
                f"{num(sft_train)} on answer tokens) and damaged the "
                f"pretrained behaviour less ({num(lora_ret)} against "
                f"{num(sft_ret)} on held-out prose). Both halves of that "
                "sentence are measurements from this run. Neither is a general "
                "law about LoRA: at 4% of a 3,048-parameter model the adapter "
                "simply does not have the capacity to overwrite much, which is "
                "exactly why it overwrites less.",
            ]
        else:
            lines += [
                "",
                "This run does NOT show the usual learn-less/forget-less "
                f"trade-off: answer loss {num(lora_train)} against "
                f"{num(sft_train)}, prose {num(lora_ret)} against "
                f"{num(sft_ret)}. Read the table, not the folklore.",
            ]
    # The trade-off is only honest if the cost side is stated as plainly as the
    # benefit side, so derive it rather than trusting prose to stay accurate.
    sft_em = None
    lora_em = None
    if isinstance(fam, dict):
        cps = _get(fam, "checkpoints") or []
        for row in _get(fam, "rows") or []:
            if (_get(row, "group") == "instruction_exact_match"
                    and _get(row, "metric") == "train"):
                vals = _get(row, "values") or []
                if "sft" in cps and cps.index("sft") < len(vals):
                    sft_em = vals[cps.index("sft")]
                if "lora" in cps and cps.index("lora") < len(vals):
                    lora_em = vals[cps.index("lora")]
    if lora_em == 0.0 and sft_em:
        lines += [
            "",
            "The cost of forgetting less, stated plainly: the LoRA checkpoint "
            f"answers {num(lora_em, 3)} of the trained instructions exactly, "
            f"against {num(sft_em, 3)} for full SFT. Halving the answer loss "
            "was not enough to produce one correct answer. 'Forgot less' here "
            "partly means 'changed less', and changing less includes not "
            "learning the task.",
        ]

    adapters = _get(run, "stages", "lora_sft", "adapters")
    if isinstance(adapters, list) and adapters:
        ranks = [_get(a, "delta_matrix_rank") for a in adapters]
        lines += [
            "",
            "The update each adapter applies is rank-constrained as advertised: "
            f"realised matrix ranks {_compact(ranks)} against a configured rank "
            f"of {num(_get(lora, 'config', 'rank'))}, attached to "
            f"{_compact(_get(lora, 'attached_to'))}.",
        ]
    return "\n".join(lines)


def section_evaluation(run: Dict[str, Any]) -> str:
    comp = _get(run, "stages", "evaluation", "comparison")
    if not isinstance(comp, dict):
        return f"Checkpoint comparison {ABSENT}."
    cps = _get(comp, "checkpoints") or []
    groups: Dict[str, List[Dict[str, Any]]] = {}
    for row in _get(comp, "rows") or []:
        groups.setdefault(str(_get(row, "group")), []).append(row)

    titles = {
        "retention": "Retention: next-token loss on the pretraining prose",
        "instruction_exact_match": "Instruction following: exact match by family",
        "task_pass_1": "Verifiable tasks: pass@1 by family",
    }
    # What the family names mean decides what the pass@1 row is evidence OF, so
    # it comes from the artifact rather than from a reader's assumption.
    meaning = _get(run, "stages", "evaluation", "reports", 0, "tasks",
                   "family_meaning")
    legend = ""
    if isinstance(meaning, dict):
        legend = table(
            ["Task family", "What it holds out"],
            [[f"`{k}`", str(v)] for k, v in meaning.items()],
        )
    decimals = {"retention": 4, "instruction_exact_match": 3, "task_pass_1": 3}
    lines: List[str] = []
    protocol = _get(run, "stages", "evaluation", "reports", 0, "protocol")
    lines += [
        f"Every checkpoint is evaluated under one fixed decoding protocol "
        f"({protocol or ABSENT}), so the columns are comparable to each other.",
        "",
    ]
    for group, rows in groups.items():
        lines += [f"#### {titles.get(group, group)}", ""]
        dec = decimals.get(group, 4)
        body = [[f"`{_get(r, 'metric')}`"] +
                [num(v, dec) for v in (_get(r, "values") or [])] for r in rows]
        lines += [table(["Metric"] + [f"`{c}`" for c in cps], body), ""]
        if group == "task_pass_1" and legend:
            attempts = _get(run, "stages", "evaluation", "reports", 0, "tasks",
                            "attempts")
            lines += [legend, ""]
            if attempts is not None:
                lines += [
                    f"pass@1 here means {num(attempts)} attempt per prompt "
                    "under the protocol above, with the tokens spent recorded "
                    "per item in the artifact. It is not best-of-N.",
                    "",
                ]
    # One trained question, every checkpoint. Claims of the form "the SFT
    # checkpoint greedily produces two." belong here, where the artifact
    # supplies the string, and not in prose where nobody re-reads them.
    reports = _get(run, "stages", "evaluation", "reports") or []
    probe = _get(reports, 0, "instructions", "families", "train", "items", 0)
    if probe is not None:
        lines += [
            "#### One trained question at every checkpoint",
            "",
            f"Prompt `{_get(probe, 'prompt')}`, expected answer "
            f"`{_get(probe, 'expected')}`, same greedy protocol throughout.",
            "",
        ]
        rows = []
        for rep in reports:
            item = _get(rep, "instructions", "families", "train", "items", 0)
            rows.append([
                f"`{_get(rep, 'checkpoint')}`",
                "`" + str(_get(item, "generated")).replace("\n", "\\n") + "`",
                "yes" if _get(item, "exact_match") else "no",
                "yes" if _get(item, "stopped_on_eos") else "no (hit the limit)",
            ])
        lines += [table(["Checkpoint", "Greedy output", "Exact match",
                         "Stopped on EOS"], rows), ""]

        # And the near-misses at the best instruction checkpoint, because "0.917"
        # hides whether the remaining failure is a typo or nonsense.
        best = None
        for rep in reports:
            score = _get(rep, "instruction_exact_match", "train")
            if score is not None and (best is None or score > best[0]):
                best = (score, rep)
        if best and best[0] > 0:
            misses = [
                it for it in
                (_get(best[1], "instructions", "families", "train", "items") or [])
                if not _get(it, "exact_match")
            ]
            if misses:
                lines += [
                    f"At `{_get(best[1], 'checkpoint')}`, the best instruction "
                    f"checkpoint ({num(best[0], 3)} exact match on the trained "
                    f"family), {len(misses)} "
                    f"{'item' if len(misses) == 1 else 'items'} still "
                    f"{'fails' if len(misses) == 1 else 'fail'}:",
                    "",
                    table(["Prompt", "Expected", "Produced"],
                          [[f"`{_get(m, 'prompt')}`", f"`{_get(m, 'expected')}`",
                            f"`{_get(m, 'generated')}`"] for m in misses]),
                    "",
                ]

    warning = _get(comp, "warning")
    if warning:
        lines += [f"_{warning}_"]
    return "\n".join(lines).rstrip()


def section_checks(run: Dict[str, Any]) -> str:
    checks = _get(run, "checks")
    if not isinstance(checks, dict):
        return f"Check results {ABSENT}."
    results = _get(checks, "results") or []
    total = _get(checks, "total")
    if total is None or not results:
        return (
            f"Check results {ABSENT}: this run carries no `checks.results` "
            "block, so this document makes no claim about what was verified. "
            "Rebuild with `python -m glassbox.export`, which runs every check "
            "and exits non-zero if any fails."
        )
    lines = [
        f"`glassbox/checks.py` runs {num(total)} numerical checks against the "
        f"live model on every run. This table is the result of the run "
        f"recorded in `runs/latest.json`: {num(_get(checks, 'passed'))} "
        f"passed, {num(_get(checks, 'failed'))} failed. Each check recomputes "
        "the quantity it is asserting about - none of them compares a stored "
        "number to itself.",
        "",
    ]
    rows = []
    for i, r in enumerate(results, start=1):
        measured = _get(r, "measured")
        if isinstance(measured, dict):
            shown = "; ".join(f"{k}={_compact(v)}" for k, v in measured.items())
        else:
            shown = _compact(measured)
        if len(shown) > 180:
            shown = shown[:179] + "\u2026"
        tol = _get(r, "tolerance")
        rows.append([
            str(i),
            f"`{_get(r, 'name')}`",
            "pass" if _get(r, "passed") else "**FAIL**",
            "-" if tol is None else _compact(tol),
            shown,
        ])
    lines.append(table(["#", "Check", "Result", "Tolerance", "Measured"], rows))
    lines += [
        "",
        "Descriptions of what each check asserts live beside the code in "
        "`glassbox/checks.py`; the artifact carries them too, under `checks."
        "results[].description`.",
    ]
    return "\n".join(lines)


def section_limits(run: Dict[str, Any]) -> str:
    lines = ["The artifact records these limits with the run:", ""]
    for limit in _get(run, "manifest", "honest_limits") or []:
        lines.append(f"- {limit}")
    if len(lines) == 2:
        lines.append(f"- {ABSENT}")

    comp = _get(run, "stages", "evaluation", "comparison")
    derived: List[str] = []
    if isinstance(comp, dict):
        cps = _get(comp, "checkpoints") or []
        by_key = {
            (str(_get(r, "group")), str(_get(r, "metric"))): (_get(r, "values") or [])
            for r in _get(comp, "rows") or []
        }

        def at(group: str, metric: str, checkpoint: str) -> Optional[float]:
            vals = by_key.get((group, metric))
            if not vals or checkpoint not in cps:
                return None
            idx = cps.index(checkpoint)
            return vals[idx] if idx < len(vals) else None

        def every(group: str, metric: str) -> Optional[List[float]]:
            return by_key.get((group, metric))

        held = every("instruction_exact_match", "heldout")
        if held is not None and max(held) == 0.0:
            derived.append(
                "Held-out instruction accuracy is "
                f"{num(0.0, 3)} at every one of the {len(held)} checkpoints. "
                "Nothing in this pipeline has demonstrated instruction "
                "following that generalises beyond the wording it was trained "
                "on."
            )
        para = every("instruction_exact_match", "paraphrase")
        if para is not None and max(para) == 0.0:
            derived.append(
                "Paraphrased versions of TRAINED questions also score "
                f"{num(0.0, 3)} everywhere. The SFT checkpoint reproduces "
                "memorised strings; it does not answer the same question "
                "asked differently."
            )
        compose = every("task_pass_1", "compose")
        if compose is not None and max(compose) == 0.0:
            derived.append(
                "The `compose` task family - two chained operations, "
                "structurally held out - is never solved: pass@1 is "
                f"{num(0.0, 3)} at every checkpoint, including after GRPO. "
                "Genuinely held-out composition is an open failure in this "
                "run, not a gap left for brevity."
            )
        sft_tr = at("instruction_exact_match", "train", "sft")
        dpo_tr = at("instruction_exact_match", "train", "dpo")
        if sft_tr is not None and dpo_tr is not None and dpo_tr < sft_tr:
            derived.append(
                "DPO reached pair accuracy "
                f"{num(_get(run, 'stages', 'dpo', 'final_accuracy'), 3)} and a "
                "margin of "
                f"{num(_get(run, 'stages', 'dpo', 'history', -1, 'margin'))} "
                "while instruction exact match on the trained family fell from "
                f"{num(sft_tr, 3)} to {num(dpo_tr, 3)}. The preference "
                "objective was optimised. The behaviour anyone cared about got "
                "worse."
            )
        add_warm = at("task_pass_1", "add", "warm_start")
        add_rl = at("task_pass_1", "add", "rl")
        tmpl_rl = at("task_pass_1", "template", "rl")
        if None not in (add_warm, add_rl, tmpl_rl) and add_rl < add_warm:
            derived.append(
                "GRPO raised pass@1 on the `template` values it was optimised "
                f"against to {num(tmpl_rl, 3)}, and in the same run pass@1 on "
                f"the warm-start `add` values fell from {num(add_warm, 3)} to "
                f"{num(add_rl, 3)}. Reward went up; the previously solved "
                "family was lost."
            )
        rl_prose = at("retention", "validation_prose_loss", "rl")
        base_prose = at("retention", "validation_prose_loss", "base")
        if None not in (rl_prose, base_prose):
            derived.append(
                "Prose validation loss at the `rl` checkpoint is "
                f"{num(rl_prose)} against {num(base_prose)} at `base`. "
                "Catastrophic forgetting here is a measurement, not a warning "
                "in a footnote."
            )
    pairs = _get(run, "stages", "reward_model", "num_pairs")
    if pairs is not None:
        derived.append(
            f"The reward model reaches ranking accuracy "
            f"{num(_get(run, 'stages', 'reward_model', 'final_accuracy'), 3)} "
            f"on the same {num(pairs)} pairs it was trained on, and is never "
            "evaluated on a held-out pair. That number measures fitting, not "
            "generalisation, and no claim about reward-model quality should be "
            "drawn from it."
        )
    if derived:
        lines += ["", "Measured in this run, and unflattering:", ""]
        lines += [f"- {d}" for d in derived]
    return "\n".join(lines)


def section_provenance(run: Dict[str, Any]) -> str:
    m = _get(run, "manifest") or {}
    checks = _get(run, "checks") or {}
    rows = [
        ("run id", _compact(_get(m, "run_id"))),
        ("artifact schema version", _compact(_get(m, "schema_version"))),
        ("seed", num(_get(m, "seed"))),
        ("dataset sha256 (all splits, instructions, preferences, tasks)",
         _full_hash(_get(m, "dataset_sha256"))),
        ("tokenizer sha256", _full_hash(_get(m, "tokenizer_sha256"))),
        ("train corpus sha256", _full_hash(_get(m, "corpus_sha256", "train"))),
        ("validation corpus sha256",
         _full_hash(_get(m, "corpus_sha256", "validation"))),
        ("PyTorch", _compact(_get(m, "torch_version"))),
        ("Python", _compact(_get(m, "python_version"))),
        ("platform", _compact(_get(m, "platform"))),
        ("device", _compact(_get(m, "device"))),
        ("total parameters", num(_get(m, "parameters"))),
        # Rounded to 10s on purpose. This is wall-clock on whatever machine
        # happened to run the build; quoting it precisely made this document
        # change on every rebuild even when every measured number was identical,
        # which destroys the point of a generated section being byte-stable.
        ("approximate build time", _approx_seconds(_get(m, "elapsed_seconds"))),
        ("numerical checks",
         f"{num(_get(checks, 'passed'))}/{num(_get(checks, 'total'))} passed"),
        ("display rounding in this document",
         f"{num(_get(m, 'display_decimals'))} decimals stored in the artifact; "
         "tables above round further for reading"),
    ]
    lines = [
        table(["Field", "Value"], [[k, v] for k, v in rows]),
        "",
        "Reproduce it with `python -m glassbox.export`, which writes "
        "`runs/<run_id>.json` and `runs/latest.json`. These are the versions "
        "this artifact was produced with, not a claim that any other version "
        "is bit-for-bit identical.",
    ]
    return "\n".join(lines)


def _full_hash(value: Any) -> str:
    if not value:
        return ABSENT
    return f"`{value}`"


#: Section name -> renderer. The keys are the marker names.
SECTIONS: Dict[str, Any] = {
    "configuration": section_configuration,
    "results": section_results,
    "lora": section_lora,
    "evaluation": section_evaluation,
    "checks": section_checks,
    "limits": section_limits,
    "provenance": section_provenance,
}

SECTION_TITLES = {
    "configuration": "Configuration as it actually ran",
    "results": "Measured results",
    "lora": "Full SFT against LoRA, measured",
    "evaluation": "Per-checkpoint evaluation",
    "checks": "Numerical checks",
    "limits": "Limits this run actually demonstrates",
    "provenance": "Provenance",
}


def render_sections(run: Dict[str, Any]) -> Dict[str, str]:
    """Render every generated section, keyed by marker name."""
    return {name: fn(run).rstrip() for name, fn in SECTIONS.items()}


def render_markdown(run: Dict[str, Any]) -> str:
    """Render every factual section as one standalone Markdown document."""
    out = [
        "# Glassbox measured results",
        "",
        "Generated from `runs/latest.json` by `python -m glassbox.report`. "
        "Every number below is read from that artifact.",
        "",
    ]
    rendered = render_sections(run)
    for name in SECTIONS:
        out += [f"## {SECTION_TITLES.get(name, name)}", "",
                rendered[name], ""]
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# In-place update of a document's generated regions
# --------------------------------------------------------------------------


def update_text(text: str, run: Dict[str, Any]) -> Tuple[str, List[str], List[str]]:
    """Replace every ``generated:<name>`` region in *text*.

    Returns the new text, the names replaced, and the names found in the
    document that this module cannot render.
    """
    rendered = render_sections(run)
    replaced: List[str] = []
    unknown: List[str] = []

    def substitute(match: "re.Match[str]") -> str:
        name = match.group("name")
        if name not in rendered:
            unknown.append(name)
            return match.group(0)
        replaced.append(name)
        return (
            f"{match.group('begin')}\n"
            f"{GENERATED_NOTE}\n\n"
            f"{rendered[name]}\n"
            f"{match.group('end')}"
        )

    return MARKER_RE.sub(substitute, text), replaced, unknown


def update_file(path: Path, run: Dict[str, Any]) -> Tuple[bool, List[str], List[str]]:
    """Rewrite *path*'s generated regions. Returns (changed, replaced, unknown)."""
    original = path.read_text(encoding="utf-8")
    updated, replaced, unknown = update_text(original, run)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
        return True, replaced, unknown
    return False, replaced, unknown


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render Glassbox factual sections from a run artifact."
    )
    parser.add_argument("--run", type=Path, default=DEFAULT_RUN,
                        help="Run artifact to read (default: runs/latest.json).")
    parser.add_argument("--update", type=Path, default=None,
                        help="Markdown file whose generated:<name> regions to replace.")
    parser.add_argument("--section", default=None, choices=sorted(SECTIONS),
                        help="Print one section instead of the whole document.")
    parser.add_argument("--list-sections", action="store_true",
                        help="List the section names this module can render.")
    args = parser.parse_args(argv)

    if args.list_sections:
        for name in SECTIONS:
            print(f"{name}\t{SECTION_TITLES.get(name, '')}")
        return 0

    if not args.run.exists():
        print(f"[report] no run artifact at {args.run}. "
              f"Build one with: python -m glassbox.export", file=sys.stderr)
        return 2
    run = load_run(args.run)

    if args.update is not None:
        if not args.update.exists():
            print(f"[report] no such file: {args.update}", file=sys.stderr)
            return 2
        changed, replaced, unknown = update_file(args.update, run)
        missing = [n for n in SECTIONS if n not in replaced]
        print(f"[report] {args.update}: "
              f"{'updated' if changed else 'already up to date'} "
              f"({len(replaced)} generated region(s) from {args.run})")
        verb = "wrote" if changed else "unchanged"
        for name in replaced:
            print(f"[report]   {verb} generated:{name}")
        for name in missing:
            print(f"[report]   note: no generated:{name} marker in the file")
        for name in sorted(set(unknown)):
            print(f"[report]   WARNING: generated:{name} has no renderer; "
                  f"left untouched", file=sys.stderr)
        return 1 if unknown else 0

    if args.section:
        print(SECTIONS[args.section](run).rstrip())
        return 0
    sys.stdout.write(render_markdown(run))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
